### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by AdedayoOpeyemi**
# Weather-App pr to Developement

This Pull request is to merge the feature branch to the development branch.

The App has the following features
 - It pulls weather forecast information using a Weather API
 -  Users can toggle based on the unit of measure of choice
 - It displays basic weather information and relevant images that represent that weather type.
 
 The PR contains all the files needed and as required.
Live Demo: [Weather-App](https://inspiring-bose-84a6ab.netlify.app)

### CODE REVIEW

**Review by afanimartin — CHANGES_REQUESTED** [review]
## Invalid PR 🔕 🔕 🔕 
Nice work setting up the project. Unfortunately am marking this PR as invalid because you have failing linter errors.
Fix those errors then send for another review.


### Martin Afani
#### Slack: whiz25

**Review by afanimartin — CHANGES_REQUESTED** [review]
## Invalid PR 🔕 🔕 🔕 
You still haven't fixed the failing linter errors. Please make the requested changes before re-submitting.

### Martin Afani
#### Slack: whiz25

**Comment by AdedayoOpeyemi** [comment]
Hi Martin,

Thanks for your timely review of the project.

I will want to point out that those are not linter errors. That is coming from netlify failing to deploy. I have a deployed version linked within the readme and the PR.

**Review by BrianSammit — CHANGES_REQUESTED** [review]
CHANGES REQUIRED 🔴 🛑
---------------
Hello @AdedayoOpeyemi, great job working on this project 👍 
TO HIGHLIGHT: 

- The repo is professional 
- The project is professional
- The app search properly for the temperature
- 

However, there are a few changes to make to complete this project 🛠️ see them below 👀 👇 
------------

- [x] Please on your readme file, write the steps about how to start your project. 
- [x] On your pull request you don't need to copy and paste the readme file, You just need to write a brief explanation about what you did on the branch you want to merge. E.g `I create a weather app with the followings files: etc`  [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

descriptive_prs

- [x] Please use ES6 syntax. Change the function keyword to arrow functions. 

es6_requirement

- [x] I got the following error when I'm trying to start the app. 

 Capture

- [ ] When I click on the toggle to change the temperature to Celsius or Fahrenheit the temperature doesn't change. Please fix this functionality. 

-------------
Please make these required changes and send it again for another review 👍 💯 
Reachme on SLACK if you have any questions. 
@ Brian Sammit Cruz Rodriguez
HAPPY CODING!! 😄 

cat

**Comment by AdedayoOpeyemi** [comment]
> ## CHANGES REQUIRED 🔴 🛑
> Hello @AdedayoOpeyemi, great job working on this project 👍
> TO HIGHLIGHT:
> 
> * The repo is professional
> * The project is professional
> * The app search properly for the temperature
> 
> ## However, there are a few changes to make to complete this project 🛠️ see them below 👀 👇
> * [x]  Please on your readme file, write the steps about how to start your project.
> * [x]  On your pull request you don't need to copy and paste the readme file, You just need to write a brief explanation about what you did on the branch you want to merge. E.g `I create a weather app with the followings files: etc`  [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
> 
> descriptive_prs
> 
> * [x]  Please use ES6 syntax. Change the function keyword to arrow functions.
> 
> es6_requirement
> 
> * [x]  I got the following error when I'm trying to start the app.
> 
> Capture
> 
> * [ ]  When I click on the toggle to change the temperature to Celsius or Fahrenheit the temperature doesn't change. Please fix this functionality.
> 
> Please make these required changes and send it again for another review 👍 💯
> Reachme on SLACK if you have any questions.
> @ Brian Sammit Cruz Rodriguez
> HAPPY CODING!! 😄
> 
> cat

Hi,

Thanks for the review on my project.

I have fixed the changes mentioned except for the toggle between celsius and Fahrenheit. I do not believe that is part o the project requirement. 

I set mine up so that it takes in the unit parameter to be used and not for the purpose of toggling the units after the result has been gotten.

Thanks

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Changes required:full_moon::wrench::hammer:
**Hi Opeyemi!
Great job so far:clap::clap:. However, we still need to make a few changes to get the project approved:muscle:.**

**To improve**
As requested by the last reviewer:

- [ ] Please on your readme file, write the steps about how to start your project. After `cd weather-app`. You need to run `npm install` and `npm run start` to run the app. kindly fix this.
- [ ]  On your pull request you don't need to copy and paste the readme file, You just need to write a brief explanation about what you did on the branch you want to merge. E.g I create a weather app with the followings files.
- [ ] It has a toggle control to determine if the result will be shown in Celsius or Fahrenheit (There are two valid solutions: students can make two different requests for the Celsius data and the Fahrenheit data OR make only one request and use math to convert it to the other unit) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))

Make the above-required changes and when you are ready, request another review.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

**Review by BrianSammit — APPROVED** [review]
STATUS: APPROVED 🟢 👏 
-------------
Hello there again 👋 Great job implementing the required changes 👍 💪 
Now your app looks so great and works perfectly 😄
-----------
You can merge this branch now 💯 🥇 
HAPPY CODING!!!  AND GOOD LUCK WITH THE COMING ONES 🤞 🍀 

Well-Done-Applause

**Pull request merged**
